version: '3.3'

services:
  
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "3001:3001"
    container_name: client
    networks:
      - sentinel

networks:
  sentinel: